use_frameworks!

target 'DemoPod_Example' do
  pod 'DemoPod', :path => '../'

  target 'DemoPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
